//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "analyze_order_product_details")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  pub customer_code: i32,
  #[sea_orm(column_type = "Text")]
  pub custormer_type: String,
  #[sea_orm(column_type = "Text")]
  pub province: String,
  #[sea_orm(column_type = "Text")]
  pub city: String,
  #[sea_orm(column_type = "Text")]
  pub city_level: String,
  #[sea_orm(column_type = "Text")]
  pub store_type: String,
  pub store_code: i32,
  pub custromer_code: i32,
  #[sea_orm(column_type = "Text")]
  pub baby_age_group: String,
  #[sea_orm(column_type = "Text")]
  pub gender: String,
  #[sea_orm(column_type = "Text")]
  pub crowd_type: String,
  #[sea_orm(column_type = "Text")]
  pub online_order: String,
  #[sea_orm(column_type = "Text")]
  pub payment_date: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub write_off_date: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub associated_order_number: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub first_category: String,
  #[sea_orm(column_type = "Text")]
  pub secondary_category: String,
  #[sea_orm(column_type = "Text")]
  pub related_first_category: String,
  #[sea_orm(column_type = "Text")]
  pub related_secondary_category: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub brand_name: Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_brand_name: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub online_commodity_code: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub related_online_commodity_code: Option<String>,
  #[sea_orm(column_type = "Text")]
  pub marketing_campaign_type: String,
  #[sea_orm(column_type = "Text")]
  pub scene_name: String,
  pub payment_write_off_days_difference: Option<i32>,
  pub online_sales: Decimal,
  pub related_sales: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
