//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod analyze_daily_summary;
pub mod analyze_order_product_details;
pub mod chat;
pub mod dashboard;
pub mod email_code;
pub mod message;
pub mod metadata_info;
pub mod user;
pub mod vote;
