//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use common::types::message::MessagePart;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
  pub id: String,
  #[sea_orm(column_type = "Text")]
  pub chat_id: String,
  #[sea_orm(column_type = "Text")]
  pub role: String,
  #[sea_orm(column_type = "Text")]
  pub parts: String,
  #[sea_orm(column_type = "Text")]
  pub attachments: String,
  #[sea_orm(column_type = "Text")]
  pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::chat::Entity",
    from = "Column::ChatId",
    to = "super::chat::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Chat,
  #[sea_orm(has_many = "super::dashboard::Entity")]
  Dashboard,
  #[sea_orm(has_many = "super::vote::Entity")]
  Vote,
}

impl Related<super::dashboard::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Dashboard.def()
  }
}

impl Related<super::vote::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Vote.def()
  }
}

impl Related<super::chat::Entity> for Entity {
  fn to() -> RelationDef {
    super::vote::Relation::Chat.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::vote::Relation::Message.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
  pub fn parse_parts(&self) -> Result<Vec<MessagePart>, String> {
    let parts: Vec<MessagePart> = serde_json::from_str(&self.parts).map_err(|e| e.to_string())?;
    Ok(parts)
  }
}
