//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::analyze_daily_summary::Entity as AnalyzeDailySummary;
pub use super::analyze_order_product_details::Entity as AnalyzeOrderProductDetails;
pub use super::chat::Entity as Chat;
pub use super::dashboard::Entity as Dashboard;
pub use super::email_code::Entity as EmailCode;
pub use super::message::Entity as Message;
pub use super::metadata_info::Entity as MetadataInfo;
pub use super::user::Entity as User;
pub use super::vote::Entity as Vote;
